default:
  image: openjdk:16.0.2-jdk-oracle

stages:
  - build

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x ./gradlew

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

headblocks:
  stage: build
  script: ./gradlew clean build
  artifacts:
    paths:
      - build/HeadBlocks-*.jar
  only:
    - master