package fr.aerwyn81.headblocks.utils.internal;

import fr.aerwyn81.headblocks.HeadBlocks;
import fr.aerwyn81.headblocks.ServiceRegistry;
import fr.aerwyn81.headblocks.databases.EnumTypeDatabase;

import java.io.File;
import java.io.IOException;
import java.io.PrintStream;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;

public class ExportSQLHelper {

    private ExportSQLHelper() {
    }

    public static void generateFile(ServiceRegistry registry, EnumTypeDatabase enumTypeDatabase, String fileName) throws IOException, InternalException {
        File sqlFile = new File(HeadBlocks.getInstance().getDataFolder(), fileName);

        try {
            Files.deleteIfExists(sqlFile.toPath());
        } catch (IOException e) {
            LogUtil.error("Cannot delete existing SQL export file: {0}", sqlFile.getAbsolutePath());
        }

        Charset charset = StandardCharsets.UTF_8;

        try (PrintStream ps = new PrintStream(sqlFile, charset)) {
            ps.println("-- ");
            ps.println("-- File generated by HeadBlocks " + HeadBlocks.getInstance().getDescription().getVersion() + " (" +
                    LocalDateTime.now(ZoneId.systemDefault()).format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")) + ")");
            ps.println("-- Supported: MySQL, SQLite");
            ps.println("-- Encoding: " + charset.name());
            ps.println("-- For more SQL integration, please ask on the discord https://discord.gg/f3d848XsQt");
            ps.println("-- ");
            ps.println();

            var instructions = registry.getStorageService().getInstructionsExport(enumTypeDatabase);

            for (String ins : instructions) {
                ps.println(ins);
            }
        }
    }
}
