package fr.aerwyn81.headblocks.utils.internal;

import fr.aerwyn81.headblocks.HeadBlocks;
import fr.aerwyn81.headblocks.databases.EnumTypeDatabase;
import fr.aerwyn81.headblocks.services.StorageService;

import java.io.File;
import java.io.PrintStream;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class ExportSQLHelper {

    public static void generateFile(EnumTypeDatabase enumTypeDatabase, String fileName) throws Exception {
        File sqlFile = new File(HeadBlocks.getInstance().getDataFolder(), fileName);

        if (sqlFile.exists()) {
            sqlFile.delete();
        }

        Charset charset = StandardCharsets.UTF_8;

        PrintStream ps = new PrintStream(sqlFile, charset);

        ps.println("-- ");
        ps.println("-- File generated by HeadBlocks " + HeadBlocks.getInstance().getDescription().getVersion() + " (" +
                LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")) + ")");
        ps.println("-- Supported: MySQL, SQLite");
        ps.println("-- Encoding: " + charset.name());
        ps.println("-- For more SQL integration, please ask on the discord https://discord.gg/f3d848XsQt");
        ps.println("-- ");
        ps.println();

        ps.println(StorageService.getInstructionsExport(enumTypeDatabase));
        ps.close();
    }
}
