name: Qodana

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2024.3
        with:
          args: --save-report
          upload-result: true
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
